apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-service-monitor
  namespace: accelerator-ops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ai-service
  endpoints:
  - port: web
    path: /metrics
    interval: 5s
